// <auto-generated />
using System;
using AdoKt07Booking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdoKt07Booking.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260209093841_InitialBookingSchema")]
    partial class InitialBookingSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("AdoKt07Booking.Data.Models.BookingEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_time");

                    b.Property<int>("ResourceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("resource_type");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ResourceType", "ResourceId", "StartTime", "EndTime", "Status" }, "ix_bookings_resource_time_status");

                    b.ToTable("bookings", null, t =>
                        {
                            t.HasCheckConstraint("CK_bookings_time_range", "start_time < end_time");
                        });
                });

            modelBuilder.Entity("AdoKt07Booking.Data.Models.HotelRoomEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<int>("MaxOccupancy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_occupancy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("room_type");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "ux_hotel_rooms_name")
                        .IsUnique();

                    b.ToTable("hotel_rooms");
                });

            modelBuilder.Entity("AdoKt07Booking.Data.Models.RestaurantTableEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("SeatCapacity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("seat_capacity");

                    b.Property<string>("Section")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("section");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "ux_restaurant_tables_name")
                        .IsUnique();

                    b.ToTable("restaurant_tables");
                });
#pragma warning restore 612, 618
        }
    }
}
